/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2014-12-03 05:09:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web.activity;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class activity_005fsearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");

    String projectPath=request.getContextPath();
	String hql=(String)request.getAttribute("hql");
	System.out.println("hql:"+hql);

      out.write("\r\n");
      out.write("<link href=\"");
      out.print(projectPath);
      out.write("/css/web/common.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(projectPath);
      out.write("/commonRes/tcal.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(projectPath);
      out.write("/commonRes/tcal.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(projectPath);
      out.write("/JS/jquery-1.11.1.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function searchActivity(){\r\n");
      out.write("\tvar title = $(\"#title\").val();\r\n");
      out.write("\tvar endTime = $(\"#end_time\").val();\r\n");
      out.write("\t\r\n");
      out.write("    fm=document.forms[0];\t\r\n");
      out.write("    fm.target=\"result\";\r\n");
      out.write("    var action='");
      out.print(projectPath);
      out.write("/HandlerManager?handler=activityHandler&methodName=activity_search';\r\n");
      out.write("    action+=\"&title=\"+title+\"&endTime=\"+endTime;\r\n");
      out.write("    fm.action=action;\r\n");
      out.write("    fm.submit();\r\n");
      out.write("}\r\n");
      out.write("function keyDown(event){\r\n");
      out.write("\tif (event.keyCode == 13){                                    \r\n");
      out.write("\t\tsearchActivity();\r\n");
      out.write("    } \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<title>counter browse</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"\" method=\"post\">\r\n");
      out.write("<table width=100% cellspacing=\"0\" cellpadding=\"0\" >\r\n");
      out.write("\t<tr  height=25>\r\n");
      out.write("\t\t<td><font class=\"headline\">&gt;&gt;Browse &amp; Export Counter</font></td>\t\t\t\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr bgcolor=#0066FF height=25 class=\"bar\">\r\n");
      out.write("\t\t\t\t<td><b>&nbsp;Search Condition</b></td>\t\t\t\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=60 valign=top>\r\n");
      out.write("\t\t<td><table class=\"editTable\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=10% nowrap align=right class=\"editTdName\">标题:</td>\r\n");
      out.write("\t\t\t\t<td width=15% nowrap class=\"editTdValue\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"title\" onkeydown=\"keyDown(event);\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=10% nowrap align=right class=\"editTdName\">结束时间:</td>\r\n");
      out.write("\t\t\t\t<td width=15% nowrap class=\"editTdValue\"><input type=\"text\" id=\"end_time\" name=\"end_time\" class=\"tcal\" size=\"20\" readOnly>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"8\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<input name=\"search\" id=\"search\" type=\"button\" value=\"Search\" onclick=\"javascript:searchActivity();\" class=\"button\"/>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<iframe name=\"result\" src=\"\" height=900 width=100% frameborder=0 ></iframe>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
