/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2014-12-03 05:15:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web.activity;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import DB.mo.ActivityMO;
import common.FuncString;

public final class activity_005fsearchresult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write(" ");

 	String projectPath=request.getContextPath();
	ArrayList resultList = (ArrayList)request.getAttribute("resultList");
	
 
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"");
      out.print(projectPath);
      out.write("/css/web/common.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(projectPath);
      out.write("/JS/jquery-1.11.1.js\"></script>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("<!-- \r\n");
      out.write("function delActivity(id,title){\r\n");
      out.write("\tif(confirm(\"您确认删除活动:\"+title)){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(projectPath);
      out.write("/HandlerManager?handler=activityHandler&methodName=del_activity&id=\"+id,\r\n");
      out.write("\t\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\t\tdataType : \"text\", //\r\n");
      out.write("\t\t\t\tsuccess : function(data,status){\r\n");
      out.write("\t\t\t\t\tif(data == '1'){\r\n");
      out.write("\t\t\t\t\t\talert(\"活动删除成功\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#activity\"+id).hide();\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\talert(data);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(data,status,e)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\talert(e);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function edit_activity(id){\r\n");
      out.write("\tvar height=500;\r\n");
      out.write("\tvar width=800;\r\n");
      out.write("\twindow.open ('");
      out.print(projectPath);
      out.write("/HandlerManager?handler=activityHandler&methodName=edit_activity_init&id='+id+'&date='+new Date(), 'newwindow', \r\n");
      out.write("\t\t\t'height='+height+', width='+width+', top='+(screen.height-height)/2+', left='+(screen.width-width)/2+', toolbar=no, menubar=no, scrollbars=no, resizable=no,location=n o, status=no') ;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" <div id=\"divRemark\" style=\"z-index:100px;position:absolute;\r\n");
      out.write(" background:#FFF; margin:0;  width:130px; \r\n");
      out.write(" height:130px;  font-size:12px;word-wrap:break-word;\r\n");
      out.write(" line-height:20px; \r\n");
      out.write(" color:#5c5c5c; display:none;\">\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("<table width=100% bgcolor=#FFFFD5 cellspacing=\"0\" cellpadding=\"0\" >\r\n");
      out.write("\t<tr height=25 class=\"bar\">\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<b>&nbsp;Search Result</b>\t\t\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("     ");

		if(resultList == null || resultList.size()==0){
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<TR ALIGN=\"LEFT\" VALIGN=\"TOP\">\r\n");
      out.write("\t          <TD NOWRAP>没有找到记录! </TD>\r\n");
      out.write("\t         </TR>\r\n");
      out.write("\t");
 	}else{
		
	
      out.write("\r\n");
      out.write("\t\t<tr valign=top>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" class=\"editTable\">\t\t\t\r\n");
      out.write("\t\t\t<tr valign=\"middle\" class=\"subBar\">\r\n");
      out.write("\t\t\t\t<td width=15%  align=center class=\"editTd\" >标题</td>\t\t\t\r\n");
      out.write("\t\t\t\t<td width=40% align=center class=\"editTd\" >内容</td>\r\n");
      out.write("\t\t\t\t<td width=15% align=center class=\"editTd\" >创建时间</td>\r\n");
      out.write("\t\t\t\t<td width=15% align=center class=\"editTd\" >结束时间</td>\r\n");
      out.write("\t\t\t\t<td width=15% align=center class=\"editTd\" >操作</td>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				ActivityMO activityMo=null;
				for(int i=0;i<resultList.size();i++){
					activityMo = (ActivityMO)resultList.get(i);
			
      out.write("\r\n");
      out.write("\t\t\t\t<tr valign=\"middle\" id=\"activity");
      out.print(activityMo.getId());
      out.write("\">\t\r\n");
      out.write("\t\t\t\t<td  align=center class=\"editTd\" >");
      out.print(FuncString.toString(activityMo.getTitle()));
      out.write("</td>\t\t\t\r\n");
      out.write("\t\t\t\t<td align=center class=\"editTd\" >");
      out.print(FuncString.toString(activityMo.getContent()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td align=center class=\"editTd\" >");
      out.print(FuncString.toString(activityMo.getCreateTime()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td align=center class=\"editTd\" >");
      out.print(FuncString.toString(activityMo.getEndTime()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td align=center class=\"editTd\" >\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"编辑\"  onclick=\"javascript:edit_activity(");
      out.print(activityMo.getId());
      out.write(");\"/>\r\n");
      out.write("\t\t\t\t\t <input type=\"button\" onclick=\"javascript:delActivity(");
      out.print(activityMo.getId());
      out.write(',');
      out.write('\'');
      out.print(activityMo.getTitle());
      out.write("');\" value=\"删除\" />\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t");
 	}
			
      out.write("\t\t\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t");
	}
 	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\r\n");
      out.write("function checkall(){\r\n");
      out.write("//alert(chall.checked);\r\n");
      out.write("if(chall.checked){\r\n");
      out.write("\tfor(var i=0;i< document.getElementsByName(\"chk\").length;i++ ){\r\n");
      out.write("\t\tdocument.getElementsByName(\"chk\")[i].checked=\"true\";}\r\n");
      out.write("}else{\r\n");
      out.write("//alert(chall.checked);\r\n");
      out.write("\tfor(i=0;i< document.getElementsByName(\"chk\").length;i++ ){\r\n");
      out.write("\t\t//alert(txtdoc[i].checked);\r\n");
      out.write("\t\tdocument.getElementsByName(\"chk\")[i].checked=false;}\r\n");
      out.write("}\r\n");
      out.write("//checkall.checked=\"true\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
