/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2014-12-03 00:49:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import DB.mo.ManagerUserMO;
import common.ConsistentValue;
import common.FuncString;
import java.util.Date;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=gbk");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Management page </title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gbk\">\r\n");

    String projectPath=request.getContextPath();
	ManagerUserMO user = (ManagerUserMO) session.getAttribute("user");
	
	String adminShow="none";
	if(!FuncString.isEmpty(request.getAttribute("display_admin"))){
		adminShow="";
	}

      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.print(projectPath);
      out.write("/css/web/common.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".bb {border-style:solid;border-width:3px #ff9900;cursor:hand;background-color: #CCCCCC;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"marginwidth:0px;marginheight:0px;margin: 1px;\">\r\n");
      out.write("<table border=\"0\" width=\"100%\" height=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin: 0px;\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"100%\" colspan=3 height=\"50\" valign=\"top\">\r\n");
      out.write("\t\t\t<iframe name=title src=\"");
      out.print(projectPath);
      out.write("/title.jsp\" height=100% width=100% frameborder=0 scrolling=\"no\" style=\"marginwidth:0px;marginheight:0px;\"></iframe>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"28px\">\r\n");
      out.write("\t\t<td colspan=\"3\" class=\"bgcTitle\">\r\n");
      out.write("\t\t\t<table width=\"100%\" height=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin: 0px;\">\r\n");
      out.write("\t\t\t<tr class=\"bgcTitle\">\r\n");
      out.write("\t\t\t<td width=\"20%\">\r\n");
      out.write("\t\t\t\t<img id=\"show\" src=\"images/menuShow.jpg\" onClick=\"showMenu();\" style=\"display: none; cursor:pointer;\" title=\"Show the menu!\" alt=\"Show the menu!\">\r\n");
      out.write("\t\t\t\t<img id=\"unshow\" src=\"images/menuUnshow.jpg\" onClick=\"showMenu();\" style=\"display: ''; cursor:pointer;\" title=\"Hide the menu!\" alt=\"Hide the menu!\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"80%\" align=\"right\" style=\"color: #ccc;size: 12px;\">\r\n");
      out.write("\t\t\t\t");
if(user.getRole().equals(ConsistentValue.ROLE_ADMIN)){ 
      out.write("\r\n");
      out.write("\t\t\t\t<html:link action=\"user.do?buttonv=yes\" target=\"content\"><font color=\"#ffffff\">User Profile</font></html:link>\r\n");
      out.write("\t\t\t\t|\r\n");
      out.write("\t\t\t\t<html:link action=\"chgpass.do\" target=\"content\"><font color=\"#ffffff\">Change password</font></html:link>\r\n");
      out.write("\t\t\t\t|\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t<a style=\"cursor:pointer;\" href=\"#\" onClick=\"javascript:if (window.confirm('Are you sure to logout?')){window.location.href='logon.do';}\">\r\n");
      out.write("\t\t\t\t  <font color=\"#990000\"><b>Logout</b></font></a>\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr valign=\"top\">\r\n");
      out.write("\t\t<td id=\"menu\" style=\"display: '';\" width=\"126\" height=\"95%\">\t\t\r\n");
      out.write("\t\t<table height=\"0\" width=\"100%\" style=\"font-size: 12px;\">\r\n");
      out.write("\t\t\t<tr height=\"10\"><td>&nbsp;</td></tr>\r\n");
      out.write("\t\t\t<tr id=\"activity\"\r\n");
      out.write("\t\t\t\tstyle=\"display:");
      out.print(request.getAttribute("display_user") );
      out.write("\">\r\n");
      out.write("\t\t\t\t<td nowrap class=\"menu1\">\r\n");
      out.write("\t\t\t\t\t<img border=\"0\" src=\"images/spacer.gif\" width=\"1\"\theight=\"1\">\r\n");
      out.write("\t\t\t\t\t<img id=\"gif0\" width=12 height=12 src=\"images/minus.gif\" onClick=\"shrink(div0,this)\"> \r\n");
      out.write("\t\t\t\t\t活动管理\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr id=\"activity2\"\r\n");
      out.write("\t\t\t\tstyle=\"display:");
      out.print(request.getAttribute("display_user") );
      out.write("\">\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div id=\"div0\">\r\n");
      out.write("\t\t\t\t<table width=\"100%\" height=\"0\" style=\"font-size: 12px;\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td nowrap>\r\n");
      out.write("\t\t\t\t\t\t\t<img border=\"0\" src=\"./images/spacer.gif\" width=\"10\" height=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t<img width=12 height=12 src=\"./images/minus.gif\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(projectPath);
      out.write("/HandlerManager?handler=activityHandler&method=activity_add&data=");
      out.print(new Date().getTime());
      out.write("\" target=\"content\">活动添加</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td nowrap>\r\n");
      out.write("\t\t\t\t\t\t\t<img border=\"0\" src=\"./images/spacer.gif\" width=\"10\" height=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t<img width=12 height=12 src=\"./images/minus.gif\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(projectPath);
      out.write("/HandlerManager?handler=activityHandler&method=activity_maintain&data=");
      out.print(new Date().getTime());
      out.write("\" target=\"content\">活动维护</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<tr id=\"admin\"\r\n");
      out.write("\t\t\t\tstyle=\"display:");
      out.print(adminShow);
      out.write("\">\r\n");
      out.write("\t\t\t\t<td nowrap class=\"menu1\">\r\n");
      out.write("\t\t\t\t\t<img border=\"0\" src=\"./images/spacer.gif\" width=\"1\"\theight=\"1\">\r\n");
      out.write("\t\t\t\t\t<img id=\"gif1\" width=12 height=12 src=\"./images/minus.gif\" onClick=\"shrink(div30,this)\"> \r\n");
      out.write("\t\t\t\t\tAdmin\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr id=\"adminmng\"\r\n");
      out.write("\t\t\t\tstyle=\"display:");
      out.print(adminShow);
      out.write("\">\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div id=\"div30\">\r\n");
      out.write("\t\t\t\t<table style=\"font-size: 12px;\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr id=\"sysmanage\" style=\"display:");
      out.print(request.getAttribute("display_usermanage"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<td nowrap>\r\n");
      out.write("\t\t\t\t\t\t\t<img border=\"0\" src=\"./images/spacer.gif\" width=\"10\" height=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t<img width=12 height=12 src=\"./images/minus.gif\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"systemManageAction.do?method=init\" target=\"content\" onClick=\"javascript:highlight(this);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font color=#996633>System Management</font>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr id=\"usermanage\" style=\"display:");
      out.print(request.getAttribute("display_usermanage"));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<td nowrap>\r\n");
      out.write("\t\t\t\t\t\t\t<img border=\"0\" src=\"./images/spacer.gif\" width=\"10\" height=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t<img width=12 height=12 src=\"./images/minus.gif\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"searchUserAction.do?method=init\" target=\"content\" onClick=\"javascript:highlight(this);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<font color=#996633>User Management</font>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t<tr height=100%>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td height=\"100%\" width=\"3\" valign=\"middle\">\r\n");
      out.write("\t\t\t<div style=\"valign: middle;height:100%;width:4px;\" class=\"bgcTitle\">\r\n");
      out.write("\t\t\t\t<font size=\"2\"></font>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td id=\"content\" width=\"88%\"><iframe name=\"content\" src=\"\"\r\n");
      out.write("\t\t\theight=100% width=100% frameborder=0 scrolling=\"yes\"></iframe>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction userInfo(url){\r\n");
      out.write("\t\twindow.open(url,\"_blank\",'height=400,width=600,top=200,left=200,toolbar=no,menubar=no,resizable=no,location=no,scrollbars=yes');      \r\n");
      out.write("\t}\r\n");
      out.write("\tfunction highlight(_self){\r\n");
      out.write("\t\tvar menuItemL=document.links.length;\r\n");
      out.write("\t\tfor(i=0;i<menuItemL;i++){\r\n");
      out.write("\t\t\tvar munuItem=document.links[i];\r\n");
      out.write("\t\t\tmunuItem.className=\"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t_self.className='bb';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction shrink(divcon,img){\r\n");
      out.write("\t\tif(divcon.style.display==\"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\tdivcon.style.display=\"none\";\r\n");
      out.write("\t\timg.src=\"images/plus.gif\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\tdivcon.style.display=\"\";\r\n");
      out.write("\t\timg.src=\"images/minus.gif\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction showMenu(){\t\t\t\t\r\n");
      out.write("\t\tvar menuDiv=document.getElementById(\"menu\");\r\n");
      out.write("\t\tvar conTd=document.getElementById(\"con\");\r\n");
      out.write("\t\tvar show=document.getElementById(\"show\");\r\n");
      out.write("\t\tvar unshow=document.getElementById(\"unshow\");\r\n");
      out.write("\t\t//alert(\"showMenu\"+menuDiv.style.display);\r\n");
      out.write("\t\tif(menuDiv.style.display==''){\r\n");
      out.write("\t\t\tmenuDiv.style.display='none';\r\n");
      out.write("\t\t\tshow.style.display='';\r\n");
      out.write("\t\t\tunshow.style.display='none';\r\n");
      out.write("\t\t\tcon.width=\"99%\";\r\n");
      out.write("\t\t\tmenu.width=\"0\"\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tmenuDiv.style.display='';\r\n");
      out.write("\t\t\tshow.style.display='none';\r\n");
      out.write("\t\t\tunshow.style.display='';\r\n");
      out.write("\t\t\tcon.width=\"88%\";\r\n");
      out.write("\t\t\tmenu.width=\"126\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
