/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2014-12-06 04:52:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no\" />\r\n");
      out.write("    <title>注册</title>\r\n");
      out.write("    ");

    	String projectPath=request.getContextPath();
    
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(projectPath);
      out.write("/JS/jquery-1.11.1.js\"></script>\r\n");
      out.write("    <link href=\"");
      out.print(projectPath);
      out.write("/css/wap/common.css\" type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("   <style type=\"text/css\">\r\n");
      out.write("   \t#pic{\r\n");
      out.write("\t\t  margin:0 auto;\r\n");
      out.write("\t\t  width:100%;\r\n");
      out.write("\t\t  padding:0;\r\n");
      out.write("\t\t  border:1px solid #333;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t#pic img{\r\n");
      out.write("\t    max-width:100%;\r\n");
      out.write("\t\twidth:expression(document.body.clientWidth>document.getElementById(\"pic\").scrollWidth*9/10? \"780px\": \"auto\" );\r\n");
      out.write("\t\tborder:1px dashed #000;\r\n");
      out.write("\t}\r\n");
      out.write("   </style>\r\n");
      out.write("  \r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("   \t\t$(document).ready(function(){\r\n");
      out.write("   \t\t\t$(\"#register_activity\").click(function(){\r\n");
      out.write("   \t\t\t\tvar name = $(\"#name\").val();\r\n");
      out.write("   \t\t\t\tvar phone = $(\"#phone\").val();\r\n");
      out.write("   \t\t\t\tvar vocation = $(\"#vocation\").val();\r\n");
      out.write("   \t\t\t\tif(name == \"\"){\r\n");
      out.write("   \t\t\t\t\t$(\"#name\").focus();\r\n");
      out.write("   \t\t\t\t\treturn false;\r\n");
      out.write("   \t\t\t\t}\r\n");
      out.write("   \t\t\t\tif(phone == \"\"){\r\n");
      out.write("   \t\t\t\t\t$(\"#phone\").focus();\r\n");
      out.write("   \t\t\t\t\treturn false;\r\n");
      out.write("   \t\t\t\t}\r\n");
      out.write("   \t\t\t\tif(vocation == \"\"){\r\n");
      out.write("   \t\t\t\t\t$(\"#vocation\").focus();\r\n");
      out.write("   \t\t\t\t\treturn false;\r\n");
      out.write("   \t\t\t\t}\r\n");
      out.write("   \t\t\t\t$.ajax({\r\n");
      out.write("   \t\t\t\t\turl : \"");
      out.print(projectPath);
      out.write("/HandlerManager?handler=userHandler&method=reg_act_save&data=\"+new Date(),\r\n");
      out.write("   \t\t\t\t\tmethod : 'post',\r\n");
      out.write("   \t\t\t\t\tdataType : \"text\", //\r\n");
      out.write("   \t\t\t\t\tsuccess : function(data,status){\r\n");
      out.write("   \t\t\t\t\t\tvar json = eval('('+data+')');\r\n");
      out.write("   \t\t\t\t\t\talert(\"报名成功\");\r\n");
      out.write("   \t\t\t\t\t},\r\n");
      out.write("   \t\t\t\t\terror : function(data,status,e)\r\n");
      out.write("   \t\t\t\t\t{\r\n");
      out.write("   \t\t\t\t\t\talert(e);\r\n");
      out.write("   \t\t\t\t\t}\r\n");
      out.write("   \t\t\t\t});\r\n");
      out.write("   \t\t\t});\r\n");
      out.write("   \t\t});\r\n");
      out.write("   </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  <center>\r\n");
      out.write("  <table class=\"editTable\" width=\"80%\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=40% nowrap align=right class=\"editTdName\">姓名:</td>\r\n");
      out.write("\t\t<td width=60% nowrap class=\"editTdValue\"><input type=\"text\" id=\"name\"/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=40% nowrap align=right class=\"editTdName\">手机:</td>\r\n");
      out.write("\t\t<td width=60% nowrap class=\"editTdValue\"><input type=\"text\" id=\"phone\"/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=40% nowrap align=right class=\"editTdName\">职业:</td>\r\n");
      out.write("\t\t<td width=60% nowrap class=\"editTdValue\"><input type=\"text\" id=\"vocation\"/></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=100% nowrap align=right class=\"editTdName\" colspan=2>\r\n");
      out.write("\t\t\t<div id=\"pic\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(projectPath);
      out.write("/images/DSC_9648.JPG\" alt=\"感谢blueidea被我盗链图片！\"/>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t  \t<td colspan=2 align=\"center\">\r\n");
      out.write("\t\t  \t<input type=\"button\" value=\"活动报名\"  id=\"register_activity\">\r\n");
      out.write("\t\t  </td>\r\n");
      out.write("\t  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\t\r\n");
      out.write("\t</center>\t\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
