/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2014-12-04 07:59:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.web.activity;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import DB.mo.ActivityMO;
import common.FuncString;

public final class activity_005fadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>添加活动</title>\r\n");
      out.write("\r\n");

    String projectPath=request.getContextPath();
	ActivityMO mo = (ActivityMO)request.getAttribute("activity");
	boolean isEdit=false;
	if(mo==null){
		mo=new ActivityMO();
	}else{
		isEdit = true;
	}

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(projectPath);
      out.write("/commonRes/tcal.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\"  href=\"");
      out.print(projectPath);
      out.write("/css/web/common.css\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(projectPath);
      out.write("/commonRes/tcal.js\"></script> \r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(projectPath);
      out.write("/JS/jquery-1.11.1.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    \t.input{font-size:16px;color:#000000;line-height:20px;padding:10px 0;margin:-10px 0;}\r\n");
      out.write("    </style>\r\n");
      out.write("\t<SCRIPT type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\"#activity_title\").val(\"");
      out.print(FuncString.toString(mo.getTitle()));
      out.write("\");\r\n");
      out.write("\t\t$(\"#contentDesc\").val(\"");
      out.print(FuncString.toString(mo.getContent()));
      out.write("\");\r\n");
      out.write("\t\t$(\"#end_time\").val(\"");
      out.print(FuncString.toString(mo.getEndTime()));
      out.write("\");\r\n");
      out.write("\t});\r\n");
      out.write("\t//新增活动保存\r\n");
      out.write("\tfunction add_save(){\r\n");
      out.write("\t\tvar title = $(\"#activity_title\").val();\r\n");
      out.write("\t\tvar content = $(\"#contentDesc\").val();\r\n");
      out.write("\t}\r\n");
      out.write("\t//编辑活动保存\r\n");
      out.write("\tfunction edit_activity(){\r\n");
      out.write("\t\tvar id = \"");
      out.print(mo.getId());
      out.write("\";\r\n");
      out.write("\t\tvar title = $(\"#activity_title\").val();\r\n");
      out.write("\t\tvar content = $('#contentDesc').val();\r\n");
      out.write("\t\tvar endTime = $('#end_time').val();\r\n");
      out.write("\t\talert(title);\r\n");
      out.write("\t\t//var param=\"&id=\"+id+\"&activity_title=\"+title+\"&contentDesc=\"+content+\"&endTime=\"+endTime;\r\n");
      out.write("\t\tvar param=\"&id=\"+id+\"&activity_title=\"+title+\"&contentDesc=\"+content+\"&endTime=\"+endTime;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(projectPath);
      out.write("/HandlerManager?handler=activityHandler&methodName=edit_activity_save&data=\"+new Date(),\r\n");
      out.write("\t\t\t\tmethod : 'post',\r\n");
      out.write("\t\t\t\tdata:param,\r\n");
      out.write("\t\t\t\t//contentType: \"application/x-www-form-urlencoded; charset=gbk\", \r\n");
      out.write("\t\t\t\tdataType : \"text\", //\r\n");
      out.write("\t\t\t\tsuccess : function(data,status){\r\n");
      out.write("\t\t\t\t\tif(data == '1'){\r\n");
      out.write("\t\t\t\t\t\talert('信息修改成功');\r\n");
      out.write("\t\t\t\t\t\twindow.close();\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\talert(data);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(data,status,e)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\talert(e);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction isHasChinese(str){\r\n");
      out.write("\t var nlength = str.length;\r\n");
      out.write("\t var ch;\r\n");
      out.write("\t for(var i = 0; i < nlength; i++){\r\n");
      out.write("\t  ch = str.charCodeAt(i);\r\n");
      out.write("\t  if( ch > 126 )\r\n");
      out.write("\t     return true;\r\n");
      out.write("\t }\r\n");
      out.write("\t return false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</SCRIPT>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" <center>\r\n");
      out.write("\t<form action=\"");
      out.print(projectPath);
      out.write("/HandlerManager?handler=activityHandler&method=activity_add_save\" styleId=\"frm\" name=\"actForm\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"id\" value=\"");
      out.print(mo.getId());
      out.write("\">\r\n");
      out.write("\t\t<table width=80% cellspacing=\"0\" cellpadding=\"0\" >\r\n");
      out.write("\t\t\t<tr  height=25>\r\n");
      out.write("\t\t\t\t<td><font class=\"headline\">&gt;&gt;活动添加 </font></td>\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr  height=25>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=60 valign=top>\r\n");
      out.write("\t\t\t\t<td><table class=\"editTable\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr class=\"bar\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"editTdName\">\r\n");
      out.write("\t\t\t\t\t\t\t活动标题\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"editTdValue\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"activity_title\" name=\"activity_title\"  size=\"105\" maxlength=\"70\"> <font color=\"red\" size=\"4\"> * </font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr  class=\"bar\">\r\n");
      out.write("\t\t\t\t\t\t<td class=\"editTdName\">活动主要内容描述:\t</td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td  class=\"editTdValue\">\r\n");
      out.write("\t\t\t\t\t\t   <textarea id=\"contentDesc\" name=\"contentDesc\" cols=\"80\" rows=\"6\" width=\"100%\"></textarea>\r\n");
      out.write("\t\t          \t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr class=\"bar\">\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t活动截止时间\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td  class=\"editTdValue\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"end_time\" name=\"end_time\" class=\"tcal\" size=\"20\" >\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

						if(isEdit){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" style=\"cursor: pointer;\" value=\"保存\" onclick=\"javascript:edit_activity();\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
	}else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" style=\"cursor: pointer;\" value=\"保存\" onclick=\"javascript:add_save();\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
	}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write(" </form>\r\n");
      out.write(" </center>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function searchCounterDis(){\t\r\n");
      out.write("\tfm=document.forms[0];\t\r\n");
      out.write("    fm.method.value=\"searchCounterDis\"; \r\n");
      out.write("    fm.target=\"_blank\";\r\n");
      out.write("    fm.submit();\r\n");
      out.write("}\r\n");
      out.write("function exportExcel(){\t\r\n");
      out.write("    fm=document.forms[0];\t\r\n");
      out.write("    fm.method.value=\"excelCtrScrResult\"; \r\n");
      out.write("    fm.submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
